### ISSUE TITLE
Error a la hora de configurar

### ISSUE THREAD

**Issue by juangl** [arcnexus/RedFoX#5]
Cuando estoy configurando la base de datos en la consola me tira el siguiente error

`QSqlQuery::prepare: database not open`

**Comment by Ladis72** [comment]
Hola amigo les has echado un ojo a esto:
http://www.neuxsoftware.com/wiki/instalacion-de-redfox/instalacion-de-mariadb/desde-linux
yo tuve el mismo problema

**Comment by juangl** [comment]
El problema persiste después de realizar lo de dice en la wiki. El log completo es:

```
drivers:  ("QIBASE", "QSQLITE", "QMYSQL", "QMYSQL3", "QODBC", "QODBC3", "QPSQL", "QPSQL7")
QSqlQuery::prepare: database not open
QSqlDatabasePrivate::removeDatabase: connection 'Global' is still in use, all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name 'Global', old connection removed.
QSqlQuery::prepare: database not open
QSqlQuery::prepare: database not open
```
